local root = vim.fn.getcwd()
local child = vim.fn.jobstart({ vim.v.progpath, "--embed", "--headless", "-u", "NONE", "-i", "NONE" }, { rpc = true })
local function lua(code, ...)
	return vim.rpcrequest(child, "nvim_exec_lua", code, { ... })
end
local function input(keys)
	vim.rpcrequest(child, "nvim_input", keys)
	vim.wait(100)
end
local function check(code)
	assert(vim.wait(5000, function() return lua(code) end, 20), code)
end
local ok, err = pcall(function()
	lua([[
		local root = ...
		vim.opt.rtp:prepend(root)
		vim.o.columns, vim.o.lines = 120, 40
		require('codex_cli').setup({chat={history=false,command={'python3',root..'/tests/fake_server.py'}}})
		require('codex_cli.chat').open()
	]], root)
	check('return vim.fn.mode()=="i"')
	-- Match real typing: subsequent keystrokes arrive while the menu is open.
	for _, key in ipairs({ '/', 'm', 'o' }) do input(key) end
	check([[local c=vim.fn.complete_info({'items'}); return vim.fn.pumvisible()==1 and #c.items==1 and c.items[1].word=='/model']])
	check([[return vim.api.nvim_get_current_line()=='/mo']])
	input('<BS><BS>')
	check([[return #vim.fn.complete_info({'items'}).items > 1]])
	input('mo')
	check([[local c=vim.fn.complete_info({'items'}); return #c.items==1 and c.items[1].word=='/model']])
	input('<CR>')
	check('return vim.fn.mode()=="c"')
	input('2<CR>')
	check('return vim.fn.mode()=="c"')
	input('2<CR>')
	check([[local u=require('codex_cli.chat')._ui; return vim.fn.mode()=='i' and vim.inspect(vim.api.nvim_win_get_config(u.input_win).footer):find('test-beta',1,true)]])
	-- Tab expands a command without executing it.
	input('/mo')
	check('return vim.fn.pumvisible()==1')
	input('<Tab>')
	check([[return vim.api.nvim_get_current_line()=='/model' and vim.fn.mode()=='i' and vim.fn.pumvisible()==0]])
	input('<C-u>')
	input('/')
	check('return vim.fn.pumvisible()==1')
	input('<Down><Down>')
	check([[local c=vim.fn.complete_info({'selected','items'}); return c.items[c.selected+1].word=='/skills']])
	input('<Up>')
	check([[local c=vim.fn.complete_info({'selected','items'}); return c.items[c.selected+1].word=='/model']])
	input('<Esc>')
	check([[return vim.fn.pumvisible()==0 and vim.fn.mode()=='i' and require('codex_cli.chat')._ui.input_win~=nil]])
	input('<C-u>')
	for _, key in ipairs({ '$', 'c', 'o' }) do input(key) end
	check('return vim.fn.pumvisible()==1')
	check([[local items=vim.fn.complete_info({'items'}).items; for _,item in ipairs(items) do if vim.fn.strdisplaywidth(item.menu)>24 or not item.menu:find('…',1,true) or item.abbr~=item.word then return false end end; return #items>0]])
	input('<CR>')
	check([[local s=require('codex_cli.chat')._ui.session; return vim.api.nvim_get_current_line()=='$commit' and #s.messages==0]])
	input('<C-k>')
	input('gg<CR>')
	check([[local u=require('codex_cli.chat')._ui; return vim.api.nvim_get_current_win()==u.output_win and vim.api.nvim_win_get_cursor(0)[1]==vim.api.nvim_buf_line_count(u.output_buf)]])
end)
vim.fn.jobstop(child)
assert(ok, err)
print('PASS: incremental /mo suggestions, Enter executes command, Tab expands, arrow selection, Esc cancels menu, skill Enter only completes')
vim.cmd('qa!')
