local root = vim.fn.getcwd()
local child = vim.fn.jobstart({ vim.v.progpath, "--embed", "--headless", "-u", "NONE", "-i", "NONE" }, { rpc = true })
local function lua(code, ...)
	return vim.rpcrequest(child, "nvim_exec_lua", code, { ... })
end
local function input(keys)
	vim.rpcrequest(child, "nvim_input", keys)
	vim.wait(100)
end
local function check(code)
	assert(vim.wait(5000, function() return lua(code) end, 20), code)
end
local ok, err = pcall(function()
	lua([[
		local root = ...
		vim.opt.rtp:prepend(root)
		vim.o.columns, vim.o.lines = 120, 40
		require('codex_cli').setup({chat={history=false,command={'python3',root..'/tests/fake_server.py'}}})
		require('codex_cli.chat').open()
	]], root)
	check('return vim.fn.mode()=="i"')
	input('<Up>')
	check([[return vim.api.nvim_get_current_line()=='' ]])
	input('first prompt<CR>')
	check([[local s=require('codex_cli.chat')._ui.session; return not s.busy and #s.messages==2]])
	input('second<M-CR>line<CR>')
	check([[local s=require('codex_cli.chat')._ui.session; return not s.busy and #s.messages==4]])
	input('draft<Up>')
	check([[return table.concat(vim.api.nvim_buf_get_lines(0,0,-1,false),'\n')=='second\nline']])
	input('<Up><Up>')
	check([[return vim.api.nvim_get_current_line()=='first prompt']])
	input('<Down>')
	check([[return table.concat(vim.api.nvim_buf_get_lines(0,0,-1,false),'\n')=='second\nline']])
	input('<Down><Down>')
	check([[return vim.api.nvim_get_current_line()=='draft']])
	input('<Up><CR>')
	check([[local s=require('codex_cli.chat')._ui.session; return not s.busy and #s.messages==6 and s.messages[5].text=='second\nline']])
	input('<Up>')
	check([[return table.concat(vim.api.nvim_buf_get_lines(0,0,-1,false),'\n')=='second\nline']])
	input('<Down>')
	check([[return vim.api.nvim_get_current_line()=='' ]])
	lua([[require('codex_cli.chat').new()]])
	input('<Up>')
	check([[return vim.api.nvim_get_current_line()=='' ]])
end)
vim.fn.jobstop(child)
if not ok then error(err) end
print('PASS: prompt history arrows, boundaries, multiline, draft restore, resend and new conversation')
vim.cmd('qa!')
