local root = vim.fn.getcwd()
local child = vim.fn.jobstart({ vim.v.progpath, "--embed", "--headless", "-u", "NONE", "-i", "NONE" }, { rpc = true })
local function lua(code, ...)
	return vim.rpcrequest(child, "nvim_exec_lua", code, { ... })
end
local function input(keys)
	vim.rpcrequest(child, "nvim_input", keys)
	vim.wait(100)
end
local function check(code)
	assert(vim.wait(5000, function() return lua(code) end, 20), code)
end
local ok, err = pcall(function()
	lua([[
		local root = ...
		vim.opt.rtp:prepend(root)
		vim.o.columns, vim.o.lines = 120, 40
		require('codex_cli').setup({chat={history=false,command={'python3',root..'/tests/fake_server.py'}}})
		require('codex_cli.chat').open()
	]], root)
	check('return vim.fn.mode()=="i"')
	input('STREAM QUEUE_CHECK<CR>')
	check([[return require('codex_cli.chat')._ui.session.busy]])
	input('follow-up one<Tab>')
	input('follow-up two<Tab>')
	check([[local s=require('codex_cli.chat')._ui.session; return #s.queue==2 and vim.api.nvim_get_current_line()=='']])
	input('unsent draft')
	check([[local s=require('codex_cli.chat')._ui.session; return not s.busy and #s.queue==0 and #s.messages==6]])
	check([[local s=require('codex_cli.chat')._ui.session; return s.messages[3].text=='follow-up one' and s.messages[5].text=='follow-up two' and vim.api.nvim_get_current_line()=='unsent draft']])
	lua([[require('codex_cli.chat').send('HOLD')]])
	check([[return require('codex_cli.chat')._ui.session.turn~=nil]])
	input('after interruption<Tab>')
	input('<C-c>')
	check([[local s=require('codex_cli.chat')._ui.session; return not s.busy and #s.queue==1]])
	input('<Tab>')
	check([[local s=require('codex_cli.chat')._ui.session; return not s.busy and #s.queue==0 and s.messages[#s.messages-1].text=='after interruption']])
end)
vim.fn.jobstop(child)
assert(ok, err)
print('PASS: Tab queues FIFO, completion auto-sends, preserves drafts, interruption pauses and Tab resumes')
vim.cmd('qa!')
