local root = vim.fn.getcwd()
local child = vim.fn.jobstart({ vim.v.progpath, "--embed", "--headless", "-u", "NONE", "-i", "NONE" }, { rpc = true })
local function lua(code, ...)
	return vim.rpcrequest(child, "nvim_exec_lua", code, { ... })
end
local function input(keys)
	vim.rpcrequest(child, "nvim_input", keys)
	vim.wait(150)
end
local function check(code)
	assert(vim.wait(5000, function() return lua(code) end, 20), code)
end
local ok, err = pcall(function()
	lua([[
		local root = ...
		vim.opt.rtp:prepend(root)
		vim.o.columns, vim.o.lines = 120, 40
		require('codex_cli').setup({chat={history=false,command={'python3',root..'/tests/fake_server.py'}}})
		vim.api.nvim_buf_set_lines(0,0,-1,false,{'$commit inside editor context is not an explicit skill request'})
		require('codex_cli.chat').open()
	]], root)
	check('return vim.fn.mode()=="i"')
	input('$')
	check('return vim.fn.pumvisible()==1')
	check([[local items=vim.fn.complete_info({'items'}).items; return #items==3 and items[1].word=='$commit' and items[3].word=='$plugin:review']])
	input('commit-a')
	check([[local items=vim.fn.complete_info({'items'}).items; return #items==1 and items[1].word=='$commit-all']])
	input('<Tab> SKILL_CHECK<CR>')
	check([[local s=require('codex_cli.chat')._ui.session; return not s.busy and #s.messages==2 and s.messages[2].text=='skills=commit-all']])
	-- Namespaced and repeated mentions attach once; disabled/unknown names do not attach.
	input('$plugin:review $plugin:review $disabled $HOME SKILL_CHECK<CR>')
	check([[local s=require('codex_cli.chat')._ui.session; return not s.busy and #s.messages==4 and s.messages[4].text=='skills=plugin:review']])
	input('/skills<CR>')
	check('return vim.fn.mode()=="c"')
	input('1<CR>')
	check('return vim.fn.mode()=="i"')
	check([[return vim.api.nvim_get_current_line()=='$commit ']])
	input('SKILL_CHECK<CR>')
	check([[local s=require('codex_cli.chat')._ui.session; return not s.busy and #s.messages==6 and s.messages[5].text=='$commit SKILL_CHECK' and s.messages[6].text=='skills=commit']])
	input('/new<CR>')
	check([[return #require('codex_cli.chat')._ui.session.messages==0]])
	input('/unsupported<CR>')
	check([[return #require('codex_cli.chat')._ui.session.messages==0]])
	input('SKILL_CHECK<CR>')
	check([[local s=require('codex_cli.chat')._ui.session; return not s.busy and #s.messages==2 and s.messages[2].text=='skills=']])
end)
vim.fn.jobstop(child)
assert(ok, err)
print('PASS: $ completion, Tab acceptance, exact and namespaced skills, deduplication, disabled skills, editor context isolation, slash commands')
vim.cmd('qa!')
