local root = vim.fn.getcwd()
local child = vim.fn.jobstart({ vim.v.progpath, "--embed", "--headless", "-u", "NONE", "-i", "NONE" }, { rpc = true })
local function lua(code, ...)
	return vim.rpcrequest(child, "nvim_exec_lua", code, { ... })
end
local function input(keys)
	vim.rpcrequest(child, "nvim_input", keys)
	vim.wait(150)
end
local function check(code)
	assert(vim.wait(5000, function() return lua(code) end, 20), code)
end
local ok, err = pcall(function()
	lua([[
		local root = ...
		vim.opt.rtp:prepend(root)
		vim.o.columns, vim.o.lines = 120, 40
		vim.keymap.set('t','<C-j>','BROKEN')
		_G.quality_path = vim.fn.tempname()
		vim.fn.writefile({'CLI quality ONE'}, quality_path)
		require('codex_cli').setup({chat={history=false,instructions_file=quality_path,cli_command={'python3',root..'/tests/fake_tui.py'}}})
		require('codex_cli.chat').open()
		require('codex_cli.chat').cli()
	]], root)
	check('return vim.fn.mode()=="t"')
	check([[return table.concat(vim.api.nvim_buf_get_lines(0,0,-1,false),'\n'):find('READY',1,true)]])
	check([[return table.concat(vim.api.nvim_buf_get_lines(0,0,-1,false),'\n'):find('INSTRUCTIONS:CLI quality ONE',1,true)]])
	input('<Esc>')
	check([[return vim.fn.mode()=='t' and table.concat(vim.api.nvim_buf_get_lines(0,0,-1,false),'\n'):find('KEYS:1b',1,true)]])
	input('<C-j>')
	check([[return table.concat(vim.api.nvim_buf_get_lines(0,0,-1,false),'\n'):find('KEYS:0a',1,true)]])
	input('$commit /model')
	check([[return table.concat(vim.api.nvim_buf_get_lines(0,0,-1,false),'\n'):find('KEYS:24636f6d6d6974202f6d6f64656c',1,true)]])
	local buf = lua('return vim.api.nvim_get_current_buf()')
	input('<C-\\><C-n>q')
	check('return vim.bo.buftype ~= "terminal"')
	lua("vim.cmd('CodexCLI')")
	check('return vim.fn.mode()=="t"')
	assert(lua('return vim.api.nvim_get_current_buf()') == buf, 'hidden CLI session must be retained')
	lua('vim.o.columns=80; vim.o.lines=24; vim.api.nvim_exec_autocmds("VimResized",{})')
	check('return vim.api.nvim_win_get_width(0)==76')
	lua([[
		vim.fn.writefile({'CLI quality TWO'}, quality_path)
		vim.notify = function(message) _G.last_notice = message end
		require('codex_cli.tui').close()
		vim.cmd('CodexCLI')
	]])
	check([[return last_notice and last_notice:find('지침이 변경',1,true)]])
	assert(lua('return vim.api.nvim_get_current_buf()') == buf, 'changing instructions must not kill a live CLI')
	lua([[vim.fn.jobstop(vim.b.terminal_job_id)]])
	check([[return table.concat(vim.api.nvim_buf_get_lines(0,0,-1,false),'\n'):find('Process exited',1,true)]])
	lua([[require('codex_cli.tui').close(); vim.cmd('CodexCLI')]])
	check([[return table.concat(vim.api.nvim_buf_get_lines(0,0,-1,false),'\n'):find('INSTRUCTIONS:CLI quality TWO',1,true)]])
	lua([[vim.fn.delete(quality_path)]])
end)
vim.fn.jobstop(child)
assert(ok, err)
print('PASS: terminal input, hide/reopen, resize, external CLI instructions, stale-session notice, fresh instructions after restart')
vim.cmd('qa!')
